Fixing pipeline statuses

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -139,35 +139,28 @@ jobs:
                 exit 1
               fi
               
-              secrets_raw=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy)
-              if [ $? -ne 0 ]; then
-                echo "Failed to fetch secrets from AWS Secrets Manager 🚫"
-                exit 1
-              fi
+              get_secret_value() {
+                local secret_name=$1
+                local secret_value
+                secret_value=$(aws secretsmanager get-secret-value --secret-id "$secret_name" --query "SecretString" --output text)
+                if [ $? -ne 0 ]; then
+                  echo "Failed to fetch $secret_name from AWS Secrets Manager 🚫"
+                  exit 1
+                fi
+              }
               
-              secrets_str=$(echo $secrets_raw | jq -r .SecretString)
-              if [ $? -ne 0 ]; then
-                echo "Failed to extract SecretString from secrets 🚫"
-                exit 1
-              fi
-              
-              secrets=$(echo $secrets_str | jq -r .)
-              if [ $? -ne 0 ]; then
-                echo "Failed to parse the secret 🚫"
-                exit 1
-              fi
-              
-              NEO4J_HOST=$(echo $secrets | jq -r .NEO4J_HOST)
-              NEO4J_USERNAME=$(echo $secrets | jq -r .NEO4J_USERNAME)
-              NEO4J_PASSWORD=$(echo $secrets | jq -r .NEO4J_PASSWORD)
-              BASE_URL=$(echo $secrets | jq -r .BASE_URL)
-              COMMUNITY_GRAPH_HOST=$(echo $secrets | jq -r .COMMUNITY_GRAPH_HOST)
-              COMMUNITY_GRAPH_PASSWORD=$(echo $secrets | jq -r .COMMUNITY_GRAPH_PASSWORD)
-              COMMUNITY_GRAPH_USERNAME=$(echo $secrets | jq -r .COMMUNITY_GRAPH_USERNAME)
-              AUTH0_CLIENT_ID=$(echo $secrets | jq -r .AUTH0_CLIENT_ID)
-              AUTH0_CLIENT_SECRET=$(echo $secrets | jq -r .AUTH0_CLIENT_SECRET)
-              AUTH0_ISSUER_BASE_URL=$(echo $secrets | jq -r .AUTH0_ISSUER_BASE_URL)
-
+              NEO4J_HOST=$(get_secret_value "dev/graphacademy/NEO4J_HOST" | jq -r .NEO4J_HOST)
+              NEO4J_USERNAME=$(get_secret_value "dev/graphacademy/NEO4J_USERNAME" | jq -r .NEO4J_USERNAME)
+              NEO4J_PASSWORD=$(get_secret_value "dev/graphacademy/NEO4J_PASSWORD" | jq -r .NEO4J_PASSWORD)
+              BASE_URL=$(get_secret_value "dev/graphacademy/BASE_URL" | jq -r .BASE_URL)
+              COMMUNITY_GRAPH_HOST=$(get_secret_value "dev/graphacademy/COMMUNITY_GRAPH_HOST" | jq -r .COMMUNITY_GRAPH_HOST)
+              COMMUNITY_GRAPH_PASSWORD=$(get_secret_value "dev/graphacademy/COMMUNITY_GRAPH_PASSWORD" | jq -r .COMMUNITY_GRAPH_PASSWORD)
+              COMMUNITY_GRAPH_USERNAME=$(get_secret_value "dev/graphacademy/COMMUNITY_GRAPH_USERNAME" | jq -r .COMMUNITY_GRAPH_USERNAME)
+              AUTH0_CLIENT_ID=$(get_secret_value "dev/graphacademy/AUTH0_CLIENT_ID" | jq -r .AUTH0_CLIENT_ID)
+              AUTH0_CLIENT_SECRET=$(get_secret_value "dev/graphacademy/AUTH0_CLIENT_SECRET" | jq -r .AUTH0_CLIENT_SECRET)
+              AUTH0_ISSUER_BASE_URL=$(get_secret_value "dev/graphacademy/AUTH0_ISSUER_BASE_URL" | jq -r .AUTH0_ISSUER_BASE_URL)
+  
+  
               NEW_TASK_DEF=$(echo "$TASK_DEF" | jq --arg IMAGE_URI "$IMAGE_URI" \
                                                    --arg NEO4J_HOST "$NEO4J_HOST" \
                                                    --arg NEO4J_USERNAME "$NEO4J_USERNAME" \
@@ -179,21 +172,21 @@ jobs:
                                                    --arg AUTH0_CLIENT_SECRET "$AUTH0_CLIENT_SECRET" \
                                                    --arg AUTH0_ISSUER_BASE_URL "$AUTH0_ISSUER_BASE_URL" \
                                                    --arg COMMUNITY_GRAPH_USERNAME "$COMMUNITY_GRAPH_USERNAME" '
-               .taskDefinition |
-               del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) |
-               .containerDefinitions[0].image = $IMAGE_URI |
-               .containerDefinitions[0].environment = [
-                    {"name": "NEO4J_HOST", "value": $NEO4J_HOST},
-                    {"name": "NEO4J_USERNAME", "value": $NEO4J_USERNAME},
-                    {"name": "NEO4J_PASSWORD", "value": $NEO4J_PASSWORD},
-                    {"name": "BASE_URL", "value": $BASE_URL},
-                    {"name": "COMMUNITY_GRAPH_HOST", "value": $COMMUNITY_GRAPH_HOST},
-                    {"name": "COMMUNITY_GRAPH_PASSWORD", "value": $COMMUNITY_GRAPH_PASSWORD},
-                    {"name": "COMMUNITY_GRAPH_USERNAME", "value": $COMMUNITY_GRAPH_USERNAME},
-                    {"name": "AUTH0_CLIENT_ID", "value": $AUTH0_CLIENT_ID},
-                    {"name": "AUTH0_CLIENT_SECRET", "value": $AUTH0_CLIENT_SECRET},
-                    {"name": "AUTH0_ISSUER_BASE_URL", "value": $AUTH0_ISSUER_BASE_URL}
-                  ]
+              .taskDefinition |
+              del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) |
+              .containerDefinitions[0].image = $IMAGE_URI |
+              .containerDefinitions[0].environment = [
+                  {"name": "NEO4J_HOST", "value": $NEO4J_HOST},
+                  {"name": "NEO4J_USERNAME", "value": $NEO4J_USERNAME},
+                  {"name": "NEO4J_PASSWORD", "value": $NEO4J_PASSWORD},
+                  {"name": "BASE_URL", "value": $BASE_URL},
+                  {"name": "COMMUNITY_GRAPH_HOST", "value": $COMMUNITY_GRAPH_HOST},
+                  {"name": "COMMUNITY_GRAPH_PASSWORD", "value": $COMMUNITY_GRAPH_PASSWORD},
+                  {"name": "COMMUNITY_GRAPH_USERNAME", "value": $COMMUNITY_GRAPH_USERNAME},
+                  {"name": "AUTH0_CLIENT_ID", "value": $AUTH0_CLIENT_ID},
+                  {"name": "AUTH0_CLIENT_SECRET", "value": $AUTH0_CLIENT_SECRET},
+                  {"name": "AUTH0_ISSUER_BASE_URL", "value": $AUTH0_ISSUER_BASE_URL}
+                ]
               ')
               echo "$NEW_TASK_DEF"
               echo "$NEW_TASK_DEF" > new-task-def.json
