Fixing pipeline statuses

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,6 +8,7 @@ on:
       - development
 
 jobs:
+
   set_environment:
     runs-on: ubuntu-latest
     steps:
@@ -22,7 +23,7 @@ jobs:
             ENVIRONMENT=$BRANCH_NAME
           fi
           
-          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT
+          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_ENV
     outputs:
       environment: ${{ steps.environment_check.outputs.ENVIRONMENT }}
 
@@ -95,7 +96,7 @@ jobs:
 
           - name: Generate timestamp
             id: timestamp
-            run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
+            run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
 
           - name: Build and push
             uses: docker/build-push-action@v5
@@ -111,7 +112,7 @@ jobs:
             id: output_url
             run: |
               imageURL="${{ steps.login-ecr.outputs.registry }}/${{ needs.set_environment.outputs.ENVIRONMENT }}-devrel-graphacademy-repository:${{ steps.timestamp.outputs.TIMESTAMP }}"
-              echo "IMAGEURL=$imageURL" >> $GITHUB_OUTPUT
+              echo "IMAGEURL=$imageURL" >> $GITHUB_ENV
             env:
               REGISTRY: ${{ steps.login-ecr.outputs.registry }}
               ENVIRONMENT: ${{ needs.set_environment.outputs.ENVIRONMENT }}
@@ -123,18 +124,43 @@ jobs:
               IMAGE_URI="${{steps.login-ecr.outputs.registry}}/${{needs.set_environment.outputs.ENVIRONMENT}}-devrel-graphacademy-repository:${{steps.timestamp.outputs.TIMESTAMP}}"
               TASK_NAME="${{ needs.set_environment.outputs.ENVIRONMENT }}-devrel-graphacademy-task"
               TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_NAME)
-
-              # Use the AWS CLI to fetch the secret values from AWS Secrets Manager
-              NEO4J_HOST=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/NEO4J_HOST | jq -r .SecretString | jq -r .NEO4J_HOST)
-              NEO4J_USERNAME=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/NEO4J_USERNAME | jq -r .SecretString | jq -r .NEO4J_USERNAME)
-              NEO4J_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/NEO4J_PASSWORD | jq -r .SecretString | jq -r .NEO4J_PASSWORD)
-              BASE_URL=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/BASE_URL | jq -r .SecretString | jq -r .BASE_URL)
-              COMMUNITY_GRAPH_HOST=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/COMMUNITY_GRAPH_HOST | jq -r .SecretString | jq -r .COMMUNITY_GRAPH_HOST)
-              COMMUNITY_GRAPH_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/COMMUNITY_GRAPH_PASSWORD | jq -r .SecretString | jq -r .COMMUNITY_GRAPH_PASSWORD)
-              COMMUNITY_GRAPH_USERNAME=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/COMMUNITY_GRAPH_USERNAME | jq -r .SecretString | jq -r .COMMUNITY_GRAPH_USERNAME)
-              AUTH0_CLIENT_ID=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/AUTH0_CLIENT_ID | jq -r .SecretString | jq -r .AUTH0_CLIENT_ID)
-              AUTH0_CLIENT_SECRET=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/AUTH0_CLIENT_SECRET | jq -r .SecretString | jq -r .AUTH0_CLIENT_SECRET)
-              AUTH0_ISSUER_BASE_URL=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy/AUTH0_ISSUER_BASE_URL | jq -r .SecretString | jq -r .AUTH0_ISSUER_BASE_URL)
+              if [ $? -ne 0 ]; then
+                echo "Failed to describe task definition: $TASK_NAME 🚫"
+                exit 1
+              fi
+              if [ -z "$TASK_DEF" ]; then
+                echo "No task definition found for: $TASK_NAME 🚫"
+                exit 1
+              fi
+              
+              secrets_raw=$(aws secretsmanager get-secret-value --secret-id dev/graphacademy)
+              if [ $? -ne 0 ]; then
+                echo "Failed to fetch secrets from AWS Secrets Manager 🚫"
+                exit 1
+              fi
+              
+              secrets_str=$(echo $secrets_raw | jq -r .SecretString)
+              if [ $? -ne 0 ]; then
+                echo "Failed to extract SecretString from secrets 🚫"
+                exit 1
+              fi
+              
+              secrets=$(echo $secrets_str | jq -r .)
+              if [ $? -ne 0 ]; then
+                echo "Failed to parse the secret 🚫"
+                exit 1
+              fi
+              
+              NEO4J_HOST=$(echo $secrets | jq -r .NEO4J_HOST)
+              NEO4J_USERNAME=$(echo $secrets | jq -r .NEO4J_USERNAME)
+              NEO4J_PASSWORD=$(echo $secrets | jq -r .NEO4J_PASSWORD)
+              BASE_URL=$(echo $secrets | jq -r .BASE_URL)
+              COMMUNITY_GRAPH_HOST=$(echo $secrets | jq -r .COMMUNITY_GRAPH_HOST)
+              COMMUNITY_GRAPH_PASSWORD=$(echo $secrets | jq -r .COMMUNITY_GRAPH_PASSWORD)
+              COMMUNITY_GRAPH_USERNAME=$(echo $secrets | jq -r .COMMUNITY_GRAPH_USERNAME)
+              AUTH0_CLIENT_ID=$(echo $secrets | jq -r .AUTH0_CLIENT_ID)
+              AUTH0_CLIENT_SECRET=$(echo $secrets | jq -r .AUTH0_CLIENT_SECRET)
+              AUTH0_ISSUER_BASE_URL=$(echo $secrets | jq -r .AUTH0_ISSUER_BASE_URL)
 
               NEW_TASK_DEF=$(echo "$TASK_DEF" | jq --arg IMAGE_URI "$IMAGE_URI" \
                                                    --arg NEO4J_HOST "$NEO4J_HOST" \
@@ -190,7 +216,7 @@ jobs:
           role-to-assume: ${{ secrets.DEVELOPMENT_GH_OIDC_ROLE_ARN }}
           aws-region: us-east-1
 
-      - name: Install dependencies
+      - name: Install jq and yq
         run: |
           sudo apt-get update
           sudo apt-get install -y wget
@@ -199,7 +225,7 @@ jobs:
           sudo wget -qO- https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 | sudo tee /usr/bin/yq > /dev/null
           sudo chmod +x /usr/bin/yq
 
-      - name: Read YAML configurations, update Eventbridge Schedules and Targets
+      - name: Read YAML configurations, update EventBridge Schedules and Targets
         run: |
           tasks=$(yq r -j deployment-config/cron-config.yaml crons)
           
@@ -218,12 +244,24 @@ jobs:
             output="["
             for var in "${ENV_VARS_ARRAY[@]}"; do
               secret_name="dev/graphacademy/$var"
+              
               if [[ ! $secret_name =~ ^[a-zA-Z0-9/_+=.@-]+$ ]]; then
-                echo "Invalid secret name: $secret_name"
+                echo "Invalid secret name: $secret_name 🚫"
                 exit 1
               fi
+              
               secret=$(aws secretsmanager get-secret-value --secret-id "$secret_name" --region us-east-1 --query SecretString --output text)
+              if [ $? -ne 0 ]; then
+                echo "Failed to fetch secret: $secret_name 🚫"
+                exit 1
+              fi
+          
               value=$(echo $secret | jq -r ".\"$var\"")
+              if [ $? -ne 0 ]; then
+                echo "Failed to parse json value for: $var 🚫"
+                exit 1
+              fi
+          
               env_var="{\"name\":\"$var\",\"value\":\"$value\"}"
               output+="$env_var,"
             done
@@ -249,7 +287,15 @@ jobs:
             target_arn="arn:aws:ecs:us-east-1:${AWS_ACCOUNT_ID}:cluster/${cluster_name}"  
           
             aws events put-rule --name $RULE_NAME --schedule-expression "$CRON"
-            aws events put-targets --rule $RULE_NAME --targets "Id=${ENV_NAME}-${NAME}-task-cron,Arn=${target_arn},RoleArn=${EVENTBRIDGE_ROLE},EcsParameters={TaskDefinitionArn=${task_arn}}"
+          
+            put_targets_response=$(aws events put-targets --rule $RULE_NAME --targets "Id=${ENV_NAME}-${NAME}-task-cron,Arn=${target_arn},RoleArn=${EVENTBRIDGE_ROLE},EcsParameters={TaskDefinitionArn=${task_arn}}")          
+            echo "FailedEntryCount: $(echo $put_targets_response | jq -r '.FailedEntryCount')"
+            if [ "$(echo $put_targets_response | jq -r '.FailedEntryCount')" -ne 0 ]; then
+              echo "Failed to set targets"
+              exit 1
+            else
+              echo "Target was added successfully ✅"
+            fi
           done
   
     
